rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
before_script:
  - gem install minitest
  - sh bootstrap
  - ruby extconf.rb
  - make
script: "export LD_LIBRARY_PATH=`rvm config-get libdir`:$LD_LIBRARY_PATH && rake"
matrix:
  allow_failures:
    - rvm: ruby-head
